(in-package #:org.shirakumo.framebuffers.wayland)

(defvar *moddef-table* '((:control -1 "Control")
                         (:alt -1 "Mod1")
                         (:shift -1 "Shift")
                         (:super -1 "Mod4")
                         (:caps-lock -1 "Lock")
                         (:num-lock -1 "Mod2")
                         (:scroll-lock -1 "Mod3")
                         (:hyper -1 "Mod5")))
