(in-package #:org.shirakumo.framebuffers.win32.cffi)

(cffi:define-foreign-library user32
  (T (:default "user32")))

(cffi:define-foreign-library shcore
  (T (:default "shcore")))

(cffi:define-foreign-library gdi32
  (T (:default "gdi32")))

(defconstant ENUM-CURRENT-SETTINGS (ldb (byte 32 0) -1))
(defconstant ENUM-REGISTRY-SETTINGS (ldb (byte 32 0) -2))

(cffi:defbitfield display-setting-flags
  (:updateregistry #x00000001)
  (:test #x00000002)
  (:fullscreen #x00000004)
  (:global #x00000008)
  (:set-primary #x00000010)
  (:videoparameters #x00000020)
  (:enable-unsafe-modes #x00000100)
  (:disable-unsafe-modes #x00000200)
  (:reset #x40000000)
  (:reset-ex #x20000000)
  (:noreset #x10000000))

(cffi:defbitfield global-alloc-flags
  (:fixed #x0)
  (:moveable #x2)
  (:zeroint #x40))

(cffi:defcenum (clipboard-format :int :allow-undeclared-values t)
  (:text 1)
  (:bitmap 2)
  (:metafilepict 3)
  (:sylk 4)
  (:dif 5)
  (:tiff 6)
  (:oemtext 7)
  (:dib 8)
  (:palette 9)
  (:pendata 10)
  (:riff 11)
  (:wave 12)
  (:unicodetext 13)
  (:enhmetafile 14)
  (:hdrop 15)
  (:locale 16)
  (:dibv5 17)
  (:ownerdisplay #x0080)
  (:dsptext #x0081)
  (:dspbitmap #x0082)
  (:dspmetafilepict #x0083)
  (:dspenhmetafile #x008e)
  (:privatefirst #x0200)
  (:privatelast #x02ff)
  (:gdiobjfirst #x0300)
  (:gdiobjlast #x03ff))

(cffi:defcenum load-image-type
  (:bitmap 0)
  (:icon 1)
  (:cursor 2)
  (:enhmetafile 3))

(cffi:defbitfield load-image-behavior
  (:defaultcolor #x0000)
  (:monochrome #x0001)
  (:color #x0002)
  (:copyreturnorg #x0004)
  (:copydeleteorg #x0008)
  (:loadfromfile #x0010)
  (:loadtransparent #x0020)
  (:defaultsize #x0040)
  (:vgacolor #x0080)
  (:loadmap3dcolors #x1000)
  (:createdibsection #x2000)
  (:copyfromresource #x4000)
  (:shared #x8000))

(cffi:defcenum (cursor :size)
  (:normal 32512)
  (:ibeam 32513)
  (:wait 32514)
  (:cross 32515)
  (:up 32516)
  (:size 32640)
  (:icon 32641)
  (:sizenwse 32642)
  (:sizenesw 32643)
  (:sizewe 32644)
  (:sizens 32645)
  (:sizeall 32646)
  (:icocur 32647)
  (:no 32648)
  (:hand 32649)
  (:appstarting 32650))

(cffi:defcenum (map-virtual-key-type :uint32)
  (:vk-to-vsc 0)
  (:vsc-to-vk 1)
  (:vk-to-char 2)
  (:vsc-to-vk-ex 3)
  (:vk-to-vsc-ex 4))

(cffi:defcenum (monitor-from-flags :uint32)
  (:default-to-nearest 2)
  (:default-to-null 0)
  (:default-to-primary 1))

(cffi:defbitfield (queue-status-flags :uint32)
  (:allevents #x000004BF)
  (:allinput #x000004FF)
  (:allpostmessage #x00000100)
  (:hotkey #x00000080)
  (:input #x00000407)
  (:key #x00000001)
  (:mouse #x00000006)
  (:mousebutton #x00000004)
  (:mousemove #x00000002)
  (:paint #x00000020)
  (:postmessage #x00000008)
  (:rawinput #x00000400)
  (:sendmessage #x00000040)
  (:timer #x00000010))

(cffi:defbitfield (peek-message-remove-type :uint32)
  (:noremove #x00000000)
  (:remove #x00000001)
  (:noyield #x00000002)
  (:qs-input #x04070000)
  (:qs-postmessage #x00980000)
  (:qs-paint #x00200000)
  (:qs-sendmessage #x00400000))

(cffi:defcenum monitor-dpi-type
  (:effective-dpi 0)
  (:angular-dpi 1)
  (:raw-dpi 2))

(cffi:defcenum dpi-awareness ;; PROCESS_DPI_AWARENESS
  (:unaware 0)
  (:system-dpi-aware 1)
  (:per-monitor-dpi-aware 2))

(cffi:defcenum (dpi-awareness-context :intptr) ;; DPI_AWARENESS_CONTEXT
  (:unaware -1)
  (:system-aware -2)
  (:per-monitor-aware -3)
  (:per-monitor-aware-2 -4)
  (:unaware-gdiscaled -5))

(cffi:defcenum (key :int)
  (:lbutton #x01)
  (:rbutton #x02)
  (:cancel #x03)
  (:mbutton #x04)
  (:xbutton1 #x05)
  (:xbutton2 #x06)
  (:back #x08)
  (:tab #x09)
  (:clear #x0c)
  (:return #x0d)
  (:shift #x10)
  (:control #x11)
  (:menu #x12)
  (:pause #x13)
  (:capital #x14)
  (:kana #x15)
  (:hangeul #x15)
  (:hangul #x15)
  (:ime-on #x16)
  (:junja #x17)
  (:final #x18)
  (:hanja #x19)
  (:kanji #x19)
  (:ime-off #x1a)
  (:escape #x1b)
  (:convert #x1c)
  (:nonconvert #x1d)
  (:accept #x1e)
  (:modechange #x1f)
  (:space #x20)
  (:prior #x21)
  (:next #x22)
  (:end #x23)
  (:home #x24)
  (:left #x25)
  (:up #x26)
  (:right #x27)
  (:down #x28)
  (:select #x29)
  (:print #x2a)
  (:execute #x2b)
  (:snapshot #x2c)
  (:insert #x2d)
  (:delete #x2e)
  (:help #x2f)
  (:lwin #x5b)
  (:rwin #x5c)
  (:apps #x5d)
  (:sleep #x5f)
  (:numpad0 #x60)
  (:numpad1 #x61)
  (:numpad2 #x62)
  (:numpad3 #x63)
  (:numpad4 #x64)
  (:numpad5 #x65)
  (:numpad6 #x66)
  (:numpad7 #x67)
  (:numpad8 #x68)
  (:numpad9 #x69)
  (:multiply #x6a)
  (:add #x6b)
  (:separator #x6c)
  (:subtract #x6d)
  (:decimal #x6e)
  (:divide #x6f)
  (:f1 #x70)
  (:f2 #x71)
  (:f3 #x72)
  (:f4 #x73)
  (:f5 #x74)
  (:f6 #x75)
  (:f7 #x76)
  (:f8 #x77)
  (:f9 #x78)
  (:f10 #x79)
  (:f11 #x7a)
  (:f12 #x7b)
  (:f13 #x7c)
  (:f14 #x7d)
  (:f15 #x7e)
  (:f16 #x7f)
  (:f17 #x80)
  (:f18 #x81)
  (:f19 #x82)
  (:f20 #x83)
  (:f21 #x84)
  (:f22 #x85)
  (:f23 #x86)
  (:f24 #x87)
  (:navigation-view #x88)
  (:navigation-menu #x89)
  (:navigation-up #x8a)
  (:navigation-down #x8b)
  (:navigation-left #x8c)
  (:navigation-right #x8d)
  (:navigation-accept #x8e)
  (:navigation-cancel #x8f)
  (:numlock #x90)
  (:scroll #x91)
  (:oem-nec-equal #x92)
  (:oem-fj-jisho #x92)
  (:oem-fj-masshou #x93)
  (:oem-fj-touroku #x94)
  (:oem-fj-loya #x95)
  (:oem-fj-roya #x96)
  (:lshift #xa0)
  (:rshift #xa1)
  (:lcontrol #xa2)
  (:rcontrol #xa3)
  (:lmenu #xa4)
  (:rmenu #xa5)
  (:browser-back #xa6)
  (:browser-forward #xa7)
  (:browser-refresh #xa8)
  (:browser-stop #xa9)
  (:browser-search #xaa)
  (:browser-favorites #xab)
  (:browser-home #xac)
  (:volume-mute #xad)
  (:volume-down #xae)
  (:volume-up #xaf)
  (:media-next-track #xb0)
  (:media-prev-track #xb1)
  (:media-stop #xb2)
  (:media-play-pause #xb3)
  (:launch-mail #xb4)
  (:launch-media-select #xb5)
  (:launch-app1 #xb6)
  (:launch-app2 #xb7)
  (:oem-1 #xba)
  (:oem-plus #xbb)
  (:oem-comma #xbc)
  (:oem-minus #xbd)
  (:oem-period #xbe)
  (:oem-2 #xbf)
  (:oem-3 #xc0)
  (:gamepad-a #xc3)
  (:gamepad-b #xc4)
  (:gamepad-x #xc5)
  (:gamepad-y #xc6)
  (:gamepad-right-shoulder #xc7)
  (:gamepad-left-shoulder #xc8)
  (:gamepad-left-trigger #xc9)
  (:gamepad-right-trigger #xca)
  (:gamepad-dpad-up #xcb)
  (:gamepad-dpad-down #xcc)
  (:gamepad-dpad-left #xcd)
  (:gamepad-dpad-right #xce)
  (:gamepad-menu #xcf)
  (:gamepad-view #xd0)
  (:gamepad-left-thumbstick-button #xd1)
  (:gamepad-right-thumbstick-button #xd2)
  (:gamepad-left-thumbstick-up #xd3)
  (:gamepad-left-thumbstick-down #xd4)
  (:gamepad-left-thumbstick-right #xd5)
  (:gamepad-left-thumbstick-left #xd6)
  (:gamepad-right-thumbstick-up #xd7)
  (:gamepad-right-thumbstick-down #xd8)
  (:gamepad-right-thumbstick-right #xd9)
  (:gamepad-right-thumbstick-left #xda)
  (:oem-4 #xdb)
  (:oem-5 #xdc)
  (:oem-6 #xdd)
  (:oem-7 #xde)
  (:oem-8 #xdf)
  (:oem-ax #xe1)
  (:oem-102 #xe2)
  (:ico-help #xe3)
  (:ico-00 #xe4)
  (:processkey #xe5)
  (:ico-clear #xe6)
  (:packet #xe7)
  (:oem-reset #xe9)
  (:oem-jump #xea)
  (:oem-pa1 #xeb)
  (:oem-pa2 #xec)
  (:oem-pa3 #xed)
  (:oem-wsctrl #xee)
  (:oem-cusel #xef)
  (:oem-attn #xf0)
  (:oem-finish #xf1)
  (:oem-copy #xf2)
  (:oem-auto #xf3)
  (:oem-enlw #xf4)
  (:oem-backtab #xf5)
  (:attn #xf6)
  (:crsel #xf7)
  (:exsel #xf8)
  (:ereof #xf9)
  (:play #xfa)
  (:zoom #xfb)
  (:noname #xfc)
  (:pa1 #xfd)
  (:oem-clear #xfe))

(cffi:defcenum (message-type :uint :allow-undeclared-values T)
  (:null #x0000)
  (:create #x0001)
  (:destroy #x0002)
  (:move #x0003)
  (:size #x0005)
  (:activate #x0006)
  (:setfocus #x0007)
  (:killfocus #x0008)
  (:enable #x000a)
  (:setredraw #x000b)
  (:settext #x000c)
  (:gettext #x000d)
  (:gettextlength #x000e)
  (:paint #x000f)
  (:close #x0010)
  (:queryendsession #x0011)
  (:queryopen #x0013)
  (:endsession #x0016)
  (:quit #x0012)
  (:erasebkgnd #x0014)
  (:syscolorchange #x0015)
  (:showwindow #x0018)
  (:settingchange #x001a)
  (:devmodechange #x001b)
  (:activateapp #x001c)
  (:fontchange #x001d)
  (:timechange #x001e)
  (:cancelmode #x001f)
  (:setcursor #x0020)
  (:mouseactivate #x0021)
  (:childactivate #x0022)
  (:queuesync #x0023)
  (:getminmaxinfo #x0024)
  (:painticon #x0026)
  (:iconerasebkgnd #x0027)
  (:nextdlgctl #x0028)
  (:spoolerstatus #x002a)
  (:drawitem #x002b)
  (:measureitem #x002c)
  (:deleteitem #x002d)
  (:vkeytoitem #x002e)
  (:chartoitem #x002f)
  (:setfont #x0030)
  (:getfont #x0031)
  (:sethotkey #x0032)
  (:gethotkey #x0033)
  (:querydragicon #x0037)
  (:compareitem #x0039)
  (:getobject #x003d)
  (:compacting #x0041)
  (:commnotify #x0044)
  (:windowposchanging #x0046)
  (:windowposchanged #x0047)
  (:power #x0048)
  (:copydata #x004a)
  (:canceljournal #x004b)
  (:notify #x004e)
  (:inputlangchangerequest #x0050)
  (:inputlangchange #x0051)
  (:tcard #x0052)
  (:help #x0053)
  (:userchanged #x0054)
  (:notifyformat #x0055)
  (:contextmenu #x007b)
  (:stylechanging #x007c)
  (:stylechanged #x007d)
  (:displaychange #x007e)
  (:geticon #x007f)
  (:seticon #x0080)
  (:nccreate #x0081)
  (:ncdestroy #x0082)
  (:nccalcsize #x0083)
  (:nchittest #x0084)
  (:ncpaint #x0085)
  (:ncactivate #x0086)
  (:getdlgcode #x0087)
  (:syncpaint #x0088)
  (:ncmousemove #x00a0)
  (:nclbuttondown #x00a1)
  (:nclbuttonup #x00a2)
  (:nclbuttondblclk #x00a3)
  (:ncrbuttondown #x00a4)
  (:ncrbuttonup #x00a5)
  (:ncrbuttondblclk #x00a6)
  (:ncmbuttondown #x00a7)
  (:ncmbuttonup #x00a8)
  (:ncmbuttondblclk #x00a9)
  (:ncxbuttondown #x00ab)
  (:ncxbuttonup #x00ac)
  (:ncxbuttondblclk #x00ad)
  (:input-device-change #x00fe)
  (:input #x00ff)
  (:keyfirst #x0100)
  (:keydown #x0100)
  (:keyup #x0101)
  (:char #x0102)
  (:deadchar #x0103)
  (:syskeydown #x0104)
  (:syskeyup #x0105)
  (:syschar #x0106)
  (:sysdeadchar #x0107)
  (:unichar #x0109)
  (:keylast #x0109)
  (:ime-startcomposition #x010d)
  (:ime-endcomposition #x010e)
  (:ime-composition #x010f)
  (:ime-keylast #x010f)
  (:initdialog #x0110)
  (:command #x0111)
  (:syscommand #x0112)
  (:timer #x0113)
  (:hscroll #x0114)
  (:vscroll #x0115)
  (:initmenu #x0116)
  (:initmenupopup #x0117)
  (:menuselect #x011f)
  (:gesture #x0119)
  (:gesturenotify #x011a)
  (:menuchar #x0120)
  (:enteridle #x0121)
  (:menurbuttonup #x0122)
  (:menudrag #x0123)
  (:menugetobject #x0124)
  (:uninitmenupopup #x0125)
  (:menucommand #x0126)
  (:changeuistate #x0127)
  (:updateuistate #x0128)
  (:queryuistate #x0129)
  (:ctlcolormsgbox #x0132)
  (:ctlcoloredit #x0133)
  (:ctlcolorlistbox #x0134)
  (:ctlcolorbtn #x0135)
  (:ctlcolordlg #x0136)
  (:ctlcolorscrollbar #x0137)
  (:ctlcolorstatic #x0138)
  (:mousefirst #x0200)
  (:mousemove #x0200)
  (:lbuttondown #x0201)
  (:lbuttonup #x0202)
  (:lbuttondblclk #x0203)
  (:rbuttondown #x0204)
  (:rbuttonup #x0205)
  (:rbuttondblclk #x0206)
  (:mbuttondown #x0207)
  (:mbuttonup #x0208)
  (:mbuttondblclk #x0209)
  (:mousewheel #x020a)
  (:xbuttondown #x020b)
  (:xbuttonup #x020c)
  (:xbuttondblclk #x020d)
  (:mousehwheel #x020e)
  (:mouselast #x020e)
  (:parentnotify #x0210)
  (:entermenuloop #x0211)
  (:exitmenuloop #x0212)
  (:nextmenu #x0213)
  (:sizing #x0214)
  (:capturechanged #x0215)
  (:moving #x0216)
  (:powerbroadcast #x0218)
  (:devicechange #x0219)
  (:mdicreate #x0220)
  (:mdidestroy #x0221)
  (:mdiactivate #x0222)
  (:mdirestore #x0223)
  (:mdinext #x0224)
  (:mdimaximize #x0225)
  (:mditile #x0226)
  (:mdicascade #x0227)
  (:mdiiconarrange #x0228)
  (:mdigetactive #x0229)
  (:mdisetmenu #x0230)
  (:entersizemove #x0231)
  (:exitsizemove #x0232)
  (:dropfiles #x0233)
  (:mdirefreshmenu #x0234)
  (:pointerdevicechange #x238)
  (:pointerdeviceinrange #x239)
  (:pointerdeviceoutofrange #x23a)
  (:touch #x0240)
  (:ncpointerupdate #x0241)
  (:ncpointerdown #x0242)
  (:ncpointerup #x0243)
  (:pointerupdate #x0245)
  (:pointerdown #x0246)
  (:pointerup #x0247)
  (:pointerenter #x0249)
  (:pointerleave #x024a)
  (:pointeractivate #x024b)
  (:pointercapturechanged #x024c)
  (:touchhittesting #x024d)
  (:pointerwheel #x024e)
  (:pointerhwheel #x024f)
  (:pointerroutedto #x0251)
  (:pointerroutedaway #x0252)
  (:pointerroutedreleased #x0253)
  (:ime-setcontext #x0281)
  (:ime-notify #x0282)
  (:ime-control #x0283)
  (:ime-compositionfull #x0284)
  (:ime-select #x0285)
  (:ime-char #x0286)
  (:ime-request #x0288)
  (:ime-keydown #x0290)
  (:ime-keyup #x0291)
  (:mousehover #x02a1)
  (:mouseleave #x02a3)
  (:ncmousehover #x02a0)
  (:ncmouseleave #x02a2)
  (:wtssession-change #x02b1)
  (:tablet-first #x02c0)
  (:tablet-last #x02df)
  (:dpichanged #x02e0)
  (:dpichanged-beforeparent #x02e2)
  (:dpichanged-afterparent #x02e3)
  (:getdpiscaledsize #x02e4)
  (:cut #x0300)
  (:copy #x0301)
  (:paste #x0302)
  (:clear #x0303)
  (:undo #x0304)
  (:renderformat #x0305)
  (:renderallformats #x0306)
  (:destroyclipboard #x0307)
  (:drawclipboard #x0308)
  (:paintclipboard #x0309)
  (:vscrollclipboard #x030a)
  (:sizeclipboard #x030b)
  (:askcbformatname #x030c)
  (:changecbchain #x030d)
  (:hscrollclipboard #x030e)
  (:querynewpalette #x030f)
  (:paletteischanging #x0310)
  (:palettechanged #x0311)
  (:hotkey #x0312)
  (:print #x0317)
  (:printclient #x0318)
  (:appcommand #x0319)
  (:themechanged #x031a)
  (:clipboardupdate #x031d)
  (:dwmcompositionchanged #x031e)
  (:dwmncrenderingchanged #x031f)
  (:dwmcolorizationcolorchanged #x0320)
  (:dwmwindowmaximizedchange #x0321)
  (:dwmsendiconicthumbnail #x0323)
  (:dwmsendiconiclivepreviewbitmap #x0326)
  (:gettitlebarinfoex #x033f)
  (:handheldfirst #x0358)
  (:handheldlast #x035f)
  (:afxfirst #x0360)
  (:afxlast #x037f)
  (:penwinfirst #x0380)
  (:penwinlast #x038f)
  (:app #x8000)
  (:user #x0400))

(cffi:defcenum show-command
  (:hide 0)
  (:shownormal 1)
  (:normal 1)
  (:showminimized 2)
  (:showmaximized 3)
  (:maximize 3)
  (:shownoactivate 4)
  (:show 5)
  (:minimize 6)
  (:showminnoactive 7)
  (:showna 8)
  (:restore 9)
  (:showdefault 10)
  (:forceminimize 11)
  (:max 11))

(cffi:defcenum device-cap
  (:driverversion 0)
  (:technology 2)
  (:horzsize 4)
  (:vertsize 6)
  (:horzres 8)
  (:vertres 10)
  (:bitspixel 12)
  (:planes 14)
  (:numbrushes 16)
  (:numpens 18)
  (:nummarkers 20)
  (:numfonts 22)
  (:numcolors 24)
  (:pdevicesize 26)
  (:curvecaps 28)
  (:linecaps 30)
  (:polygonalcaps 32)
  (:textcaps 34)
  (:clipcaps 36)
  (:rastercaps 38)
  (:aspectx 40)
  (:aspecty 42)
  (:aspectxy 44)
  (:logpixelsx 88)
  (:logpixelsy 90)
  (:sizepalette 104)
  (:numreserved 106)
  (:colorres 108)
  (:physicalwidth 110)
  (:physicalheight 111)
  (:physicaloffsetx 112)
  (:physicaloffsety 113)
  (:scalingfactorx 114)
  (:scalingfactory 115)
  (:vrefresh 116)
  (:desktopvertres 117)
  (:desktophorzres 118)
  (:bltalignment 119)
  (:shadeblendcaps 120)
  (:colormgmtcaps 121))

(cffi:defcenum system-metric
  (:cxscreen 0)
  (:cyscreen 1)
  (:cxvscroll 2)
  (:cyhscroll 3)
  (:cycaption 4)
  (:cxborder 5)
  (:cyborder 6)
  (:cxdlgframe 7)
  (:cydlgframe 8)
  (:cyvthumb 9)
  (:cxhthumb 10)
  (:cxicon 11)
  (:cyicon 12)
  (:cxcursor 13)
  (:cycursor 14)
  (:cymenu 15)
  (:cxfullscreen 16)
  (:cyfullscreen 17)
  (:cykanjiwindow 18)
  (:mousepresent 19)
  (:cyvscroll 20)
  (:cxhscroll 21)
  (:debug 22)
  (:swapbutton 23)
  (:reserved1 24)
  (:reserved2 25)
  (:reserved3 26)
  (:reserved4 27)
  (:cxmin 28)
  (:cymin 29)
  (:cxsize 30)
  (:cysize 31)
  (:cxframe 32)
  (:cyframe 33)
  (:cxmintrack 34)
  (:cymintrack 35)
  (:cxdoubleclk 36)
  (:cydoubleclk 37)
  (:cxiconspacing 38)
  (:cyiconspacing 39)
  (:menudropalignment 40)
  (:penwindows 41)
  (:dbcsenabled 42)
  (:cmousebuttons 43)
  (:secure 44)
  (:cxedge 45)
  (:cyedge 46)
  (:cxminspacing 47)
  (:cyminspacing 48)
  (:cxsmicon 49)
  (:cysmicon 50)
  (:cysmcaption 51)
  (:cxsmsize 52)
  (:cysmsize 53)
  (:cxmenusize 54)
  (:cymenusize 55)
  (:arrange 56)
  (:cxminimized 57)
  (:cyminimized 58)
  (:cxmaxtrack 59)
  (:cymaxtrack 60)
  (:cxmaximized 61)
  (:cymaximized 62)
  (:network 63)
  (:cleanboot 67)
  (:cxdrag 68)
  (:cydrag 69)
  (:showsounds 70)
  (:cxmenucheck 71)
  (:cymenucheck 72)
  (:slowmachine 73)
  (:mideastenabled 74)
  (:mousewheelpresent 75)
  (:xvirtualscreen 76)
  (:yvirtualscreen 77)
  (:cxvirtualscreen 78)
  (:cyvirtualscreen 79)
  (:cmonitors 80)
  (:samedisplayformat 81)
  (:immenabled 82)
  (:cxfocusborder 83)
  (:cyfocusborder 84)
  (:tabletpc 86)
  (:mediacenter 87)
  (:starter 88)
  (:serverr2 89)
  (:mousehorizontalwheelpresent 91)
  (:cxpaddedborder 92)
  (:digitizer 94)
  (:maximumtouches 95)
  (:cmetrics 97)
  (:remotesession #x1000)
  (:shuttingdown #x2000)
  (:remotecontrol #x2001)
  (:caretblinkingenabled #x2002)
  (:convertibleslatemode #x2003)
  (:systemdocked #x2004))

(cffi:defcenum (get-window-long :int :allow-undeclared-values t)
  (:wndproc -4)
  (:hinstance -6)
  (:hwndparent -8)
  (:id -12)
  (:style -16)
  (:exstyle -20)
  (:userdata -21))

(cffi:defcenum cursor
  (:arrow 32512)
  (:ibeam 32513)
  (:wait 32514)
  (:cross 32515)
  (:uparrow 32516)
  (:size 32640)
  (:icon 32641)
  (:sizenwse 32642)
  (:sizenesw 32643)
  (:sizewe 32644)
  (:sizens 32645)
  (:sizeall 32646)
  (:no 32648)
  (:hand 32649)
  (:appstarting 32650)
  (:help 32651)
  (:pin 32671)
  (:person 32672))

(cffi:defbitfield window-style
  (:overlapped #x00000000)
  (:popup #x80000000)
  (:child #x40000000)
  (:minimize #x20000000)
  (:visible #x10000000)
  (:disabled #x08000000)
  (:clipsiblings #x04000000)
  (:clipchildren #x02000000)
  (:maximize #x01000000)
  (:caption #x00c00000)
  (:border #x00800000)
  (:dlgframe #x00400000)
  (:vscroll #x00200000)
  (:hscroll #x00100000)
  (:sysmenu #x00080000)
  (:thickframe #x00040000)
  (:group #x00020000)
  (:tabstop #x00010000)
  (:minimizebox #x00020000)
  (:maximizebox #x00010000)
  ;; WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX
  (:overlappedwindow #x00CF0000)
  (:tiledwindow #x00CF0000)
  ;; WS_POPUP | WS_BORDER | WS_SYSMENU
  (:popupwindow #x80880000))

(cffi:defbitfield window-style-ex
  (:dlgmodalframe #x00000001)
  (:noparentnotify #x00000004)
  (:topmost #x00000008)
  (:acceptfiles #x00000010)
  (:transparent #x00000020)
  (:mdichild #x00000040)
  (:toolwindow #x00000080)
  (:windowedge #x00000100)
  (:clientedge #x00000200)
  (:contexthelp #x00000400)
  (:right #x00001000)
  (:left #x00000000)
  (:rtlreading #x00002000)
  (:ltrreading #x00000000)
  (:leftscrollbar #x00004000)
  (:rightscrollbar #x00000000)
  (:controlparent #x00010000)
  (:staticedge #x00020000)
  (:appwindow #x00040000)
  (:layered #x00080000)
  (:noinheritlayout #x00100000)
  (:noredirectionbitmap #x00200000)
  (:layoutrtl #x00400000)
  (:composited #x02000000)
  (:noactivate #x08000000))

(cffi:defbitfield window-class-style
  (:vredraw #x0001)
  (:hredraw #x0002)
  (:dblclks #x0008)
  (:owndc #x0020)
  (:classdc #x0040)
  (:parentdc #x0080)
  (:noclose #x0200)
  (:savebits #x0800)
  (:bytealignclient #x1000)
  (:bytealignwindow #x2000)
  (:globalclass #x4000)
  (:ime #x00010000)
  (:dropshadow #x00020000))

(cffi:defbitfield (set-window-pos :uint32)
  (:nosize #x0001)
  (:nomove #x0002)
  (:nozorder #x0004)
  (:noredraw #x0008)
  (:noactivate #x0010)
  (:framechanged #x0020)
  (:showwindow #x0040)
  (:hidewindow #x0080)
  (:nocopybits #x0100)
  (:noownerzorder #x0200)
  (:nosendchanging #x0400)
  (:defererase #x2000)
  (:asyncwindowpos #x4000))

(cffi:define-foreign-type wstring-type (cffi::foreign-array-type)
  ()
  (:actual-type :uint16)
  (:simple-parser wstring))

(cffi:define-parse-method wstring (length)
  (make-instance 'wstring-type :dimensions (list length)
                 :element-type :uint16))

(int::define-cffi-translators wstring-type wstring (p v s type1)
  :from `(com:wstring->string ,p ,(if (typep type1 'wstring-type)
                                      (reduce #'* (cffi::dimensions type1))
                                      `(reduce #'* (cffi::dimensions ,type1))))
  ;; can't limit size of com:string->wstring?, translate manually
  ;; :to `(com:string->wstring ,v ,p)
  :to `(let* ((#1=#:o (babel:string-to-octets ,v :encoding :utf-16/le))
              (l (min (length #1#)
                      (* 2 (1- ,(if (typep type1 'wstring-type)
                                    (reduce #'* (cffi::dimensions type1))
                                    `(reduce #'* (cffi::dimensions ,type1))))))))
         (loop for #2=#:i below l
               do (setf (cffi:mem-aref ,p :uint8 #2#)
                        (aref #1# #2#)))
         ;; force nul-termination for now, possibly could be optional?
         (setf (cffi:mem-aref ,p :uint16 (/ l 2)) 0))
  :alloc (cffi:foreign-alloc :uint16 :count (reduce #'* (cffi::dimensions type1))))

#++
(cffi:with-foreign-object (p #++'(wstring 16)
                             :uint16 32)
  (format t "p = ~s~%" p)
  (loop for i below 32 do (setf (cffi:mem-aref p :uint16 i) i))
  (setf (cffi:mem-aref p :uint16 0) 33)
  (setf (cffi:mem-aref p :uint16 1) 0)
  (let ((a (cffi:mem-ref p '(wstring 16))))
    (setf (cffi:mem-ref p '(wstring 16)) "test")
    (let ((b (loop for i below 20 collect (cffi:mem-aref p :uint16 i)))
          (c (cffi:mem-ref p '(wstring 16))))
      (setf (cffi:mem-ref p '(wstring 16)) "defghijklmnopqrstuvwxyz")
      (list a b c
            (loop for i below 20 collect (cffi:mem-aref p :uint16 i))
            (cffi:mem-ref p '(wstring 16))))))

(cffi:defcstruct (minmax-info :conc-name minmax-info-) ;;MINMAXINFO
  (reserved-x :long)
  (reserved-y :long)
  (max-size-x :long)
  (max-size-y :long)
  (max-position-x :long)
  (max-position-y :long)
  (min-track-size-x :long)
  (min-track-size-y :long)
  (max-track-size-x :long)
  (max-track-size-y :long))

(cffi:defcstruct (window-class :conc-name window-class-) ;; WNDCLASSW
  (style window-class-style)
  (proc :pointer) ;; wndproc
  (class-extra :int32)
  (window-extra :int32)
  (instance com:hinstance)
  (icon com:hicon)
  (cursor com:hcursor)
  (background com:hbrush)
  (menu-name com:wstring)
  (class-name com:wstring))

(cffi:defcstruct (message :conc-name message-) ;; MSG
  (window com:hwnd)
  (type message-type)
  (wparameter com:wparam)
  (lparameter com:lparam)
  (time :uint32)
  (x :int32)
  (y :int32)
  (lprivate :uint32))

(cffi:defcstruct (icon-info :conc-name icon-info-) ;; ICONINFO
  (icon com:bool)
  (xhotspot :uint32)
  (yhotspot :uint32)
  (mask com:hbitmap)
  (color com:hbitmap))

(cffi:defcstruct (bitmap-info-header :conc-name bitmap-info-header-) ;; BITMAPINFOHEADER
  (size :uint32)
  (width :long)
  (height :long)
  (planes :int16)
  (bit-count :int16)
  (compression :uint32)
  (size-image :uint32)
  (x-per-meter :long)
  (y-per-meter :long)
  (color-used :uint32)
  (color-important :uint32))

;; BITMAPINFO struct is a BITMAPINFOHEADER followed by COLOR-USED RGBx

(cffi:defcstruct (bitmap-v5-header :conc-name bitmap-info-) ;; BITMAPV5HEADER
  (size :uint32)
  (width :long)
  (height :long)
  (planes :int16)
  (bit-count :int16)
  (compression :uint32)
  (size-image :uint32)
  (x-per-meter :long)
  (y-per-meter :long)
  (color-used :uint32)
  (color-important :uint32)
  (red-mask :uint32)
  (green-mask :uint32)
  (blue-mask :uint32)
  (alpha-mask :uint32)
  (cs-type :uint32)
  (cie-red-x :int32)
  (cie-red-y :int32)
  (cie-red-z :int32)
  (cie-green-x :int32)
  (cie-green-y :int32)
  (cie-green-z :int32)
  (cie-blue-x :int32)
  (cie-blue-y :int32)
  (cie-blue-z :int32)
  (gamma-red :uint32)
  (gamma-green :uint32)
  (gamma-blue :uint32)
  (intent :uint32)
  (profile-data :uint32)
  (profile-size :uint32)
  (reserved :uint32))

(cffi:defcstruct (rect :conc-name rect-) ;; RECT
  (left :long)
  (top :long)
  (right :long)
  (bottom :long))

(cffi:defbitfield (track-mouse-event-flags :uint32)
  (:cancel #x80000000)
  (:hover #x00000001)
  (:leave #x00000002)
  (:nonclient #x00000010)
  (:query #x40000000))

(cffi:defcstruct (track-mouse-event :conc-name track-mouse-event-) ;; TRACKMOUSEEVENT
  (size :uint32)
  (flags track-mouse-event-flags)
  (track com:hwnd)
  (hover-time :uint32))

(cffi:defbitfield (devmode-field-flags :uint32)
  (:specversion #x00000401)
  (:orientation #x00000001)
  (:papersize #x00000002)
  (:paperlength #x00000004)
  (:paperwidth #x00000008)
  (:scale #x00000010)
  (:position #x00000020)
  (:nup #x00000040)
  (:displayorientation #x00000080)
  (:copies #x00000100)
  (:defaultsource #x00000200)
  (:printquality #x00000400)
  (:color #x00000800)
  (:duplex #x00001000)
  (:yresolution #x00002000)
  (:ttoption #x00004000)
  (:collate #x00008000)
  (:formname #x00010000)
  (:logpixels #x00020000)
  (:bitsperpel #x00040000)
  (:pelswidth #x00080000)
  (:pelsheight #x00100000)
  (:displayflags #x00200000)
  (:displayfrequency #x00400000)
  (:icmmethod #x00800000)
  (:icmintent #x01000000)
  (:mediatype #x02000000)
  (:dithertype #x04000000)
  (:panningwidth #x08000000)
  (:panningheight #x10000000)
  (:displayfixedoutput #x20000000)
  (:interlaced #x00000002)
  (:update #x00000001)
  (:copy #x00000002)
  (:prompt #x00000004)
  (:modify #x00000008)
  (:in-buffer #x00000008)
  (:in-prompt #x00000004)
  (:out-buffer #x00000002)
  (:out-default #x00000001))

(cffi:defcstruct (device-mode :conc-name device-mode-) ;; DEVMODEW
  (device-name (wstring 32))
  (spec-version :uint16)
  (driver-version :uint16)
  (size :uint16)
  (driver-extra :uint16)
  (fields devmode-field-flags)
  (position-x :long)
  (position-y :long)
  (display-orientation :uint32)
  (display-fixed-output :uint32)
  (color :short)
  (duplex :short)
  (resolution :short)
  (option :short)
  (collate :short)
  (form-name (wstring 32))
  (log-pixels :uint16)
  (bits-per-pel :uint32)
  (pels-width :uint32)
  (pels-height :uint32)
  (display-flags :uint32)
  (display-frequency :uint32)
  (icm-method :uint32)
  (icm-intent :uint32)
  (media-type :uint32)
  (dither-type :uint32)
  (reserved-1 :uint32)
  (reserved-2 :uint32)
  (panning-width :uint32)
  (panning-height :uint32))

(cffi:defbitfield (adapter-state-flags :uint32)
  (:device-active 1)
  (:device-primary-device 4)
  (:device-mirroring-driver 8)
  (:device-vga-compatible 16)
  (:device-removable 32)
  (:device-modes-pruned 134217728))

(cffi:defcstruct (adapter :conc-name adapter-) ;; DISPLAY_DEVICEW
  (cb :uint32)
  (device-name (wstring 32))
  (device-string (wstring 128))
  (state-flags adapter-state-flags)
  (device-id (wstring 128))
  (device-key (wstring 128)))

(cffi:defcenum (dib-usage :uint32)
  (:rgb-colors 0)
  (:pal-colors 1))

(cffi:defbitfield (rop-code :uint32)
  (:blackness #x00000042)
  (:not-src-erase #x001100A6)
  (:not-src-copy #x00330008)
  (:dst-invert #x00550009)
  (:merge-paint #x00BB0226)
  (:merge-copy #x00C000CA)
  (:src-and #x008800C6)
  (:src-copy #x00CC0020)
  (:src-erase #x00440328)
  (:src-invert #x00660046)
  (:src-paint #x00EE0086)
  (:pat-copy #x00F00021)
  (:pat-invert #x005A0049)
  (:pat-paint #x00FB0A09)
  (:whiteness #x00FF0062)
  (:capture-blt #x40000000)
  (:no-mirror-bitmap #x80000000))

(cffi:defcfun (adjust-window-rect "AdjustWindowRect") com:bool
  (rect (:pointer (:struct rect)))
  (style window-style)
  (menu com:bool))

(cffi:defcfun (bit-blt "BitBlt") com:bool
  (hdc com:hdc)
  (x :int32)
  (y :int32)
  (cx :int32)
  (cy :int32)
  (hdc-src :pointer)
  (x1 :int32)
  (y1 :int32)
  (rop rop-code))

(cffi:defcfun (bring-window-to-top "BringWindowToTop") com:bool
  (window com:hwnd))

(cffi:defcenum (disp-change :int32)
  (:successful 0)
  (:restart 1)
  (:failed -1)
  (:badmode -2)
  (:notupdated -3)
  (:badflags -4)
  (:badparam -5)
  (:baddualview -6))

(cffi:defcfun (change-display-settings "ChangeDisplaySettingsExW") disp-change
  (device-name com:wstring)
  (dev-mode (:pointer (:struct device-mode)))
  (window com:hwnd)
  (flags display-setting-flags)
  (param (:pointer :void)))

(cffi:defcfun (create-window "CreateWindowExW") com:hwnd
  (ex-style window-style-ex)
  (class-name com:wstring)
  (window-name com:wstring)
  (style window-style)
  (x :int32)
  (y :int32)
  (w :int32)
  (h :int32)
  (parent com:hwnd)
  (menu com:hmenu)
  (instance com:hinstance)
  (param (:pointer :void)))

(cffi:defcfun (def-window-proc "DefWindowProcW") :size
  (window com:hwnd)
  (message message-type)
  (wparameter com:wparam)
  (lparameter com:lparam))

(cffi:defcfun (destroy-window "DestroyWindow") com:bool
  (window com:hwnd))

(cffi:defcfun (dispatch-message "DispatchMessageW") com:lresult
  (message (:pointer (:struct message))))

(cffi:defcfun (enable-non-client-dpi-scaling "EnableNonClientDpiScaling") com:bool
  (window com:hwnd))

(cffi:defcfun (enum-display-settings "EnumDisplaySettingsW") com:bool
  (device-name com:wstring)
  (mode-num :uint32)
  (dev-mode (:pointer (:struct device-mode))))

(cffi:defcfun (enum-display-devices "EnumDisplayDevicesW") com:bool
  (device com:wstring)
  (index :uint32)
  (output (:pointer (:struct adapter)))
  (flags :uint32))

(cffi:defcfun (flash-window "FlashWindow") com:bool
  (window com:hwnd)
  (invert com:bool))

(cffi:defcfun (get-class "GetClassLongPtrW") :size
  (window com:hwnd)
  (index :int))

(cffi:defcfun (get-class-info "GetClassInfoW") com:bool
  (hinstance com:hinstance)
  (class-name com:wstring)
  (class (:pointer (:struct window-class))))

(cffi:defcfun (get-dc "GetDC") com:hdc
  (window com:hwnd))

(cffi:defcfun (get-device-caps "GetDeviceCaps") :int32
  (dc com:hdc)
  (cap device-cap))

(cffi:defcfun (get-dpi-for-monitor "GetDpiForMonitor") com:hresult
  (monitor com:hmonitor)
  (dpi-type monitor-dpi-type)
  (x (:pointer :uint32))
  (y (:pointer :uint32)))

(cffi:defcfun (get-dpi-for-window "GetDpiForWindow") :uint32
  (window com:hwnd))

(cffi:defcfun (get-message-time "GetMessageTime") :int32)

(cffi:defcfun (get-module-handle "GetModuleHandleW") com:hmodule
  (arg com:wstring))

(cffi:defcfun (get-key-state "GetKeyState") :short
  (key key))

(cffi:defcfun (get-system-metrics "GetSystemMetrics") :int32
  (index system-metric))

(cffi:defcfun (get-window "GetWindowLongW") :int32
  (window com:hwnd)
  (index get-window-long))

(cffi:defcfun (get-window-rect "GetWindowRect") com:bool
  (window com:hwnd)
  (rect (:pointer (:struct rect))))

(cffi:defcfun (invalidate-rect "InvalidateRect") com:bool
  (window com:hwnd)
  (rect (:pointer (:struct rect)))
  (erase com:bool))

(cffi:defcfun (load-cursor "LoadCursorW") com:hcursor
  (window com:hwnd)
  (cursor-name cursor))

(cffi:defcfun (load-cursor* "LoadCursorW") com:hcursor
  (window com:hwnd)
  (cursor com:wstring))

(cffi:defcfun (map-virtual-key "MapVirtualKeyW") :uint32
  (code :uint32)
  (map-type map-virtual-key-type))

(cffi:defcfun (monitor-from-window "MonitorFromWindow") com:hmonitor
  (window com:hwnd)
  (flags monitor-from-flags))

(cffi:defcfun (move-window "MoveWindow") com:bool
  (window com:hwnd)
  (x :int32)
  (y :int32)
  (w :int32)
  (h :int32)
  (repaint com:bool))

(cffi:defcfun (msg-wait-for-multiple-objects "MsgWaitForMultipleObjects") :uint32
  (count :uint32)
  (handles (:pointer com:handle))
  (wait-all com:bool)
  (milliseconds :uint32)
  (wake-mask queue-status-flags))

(cffi:defcfun (peek-message "PeekMessageW") com:bool
  (message (:pointer (:struct message)))
  (window com:hwnd)
  (message-filter-min :uint32)
  (message-filter-max :uint32)
  (remove-message peek-message-remove-type))

(cffi:defcfun (register-class "RegisterClassW") :uint16
  (class (:pointer (:struct window-class))))

(cffi:defcfun (unregister-class "UnregisterClassW") com:bool
  (name com:wstring)
  (hinstance com:hinstance))

(cffi:defcfun (release-dc "ReleaseDC") :int32
  (window com:hwnd)
  (dc com:hdc))

(cffi:defcfun (send-message "SendMessageW") com:lresult
  (window com:hwnd)
  (message message-type)
  (wparameter com:wparam)
  (lparameter com:lparam))

(cffi:defcfun (set-focus "SetFocus") com:hwnd
  (window com:hwnd))

(cffi:defcfun (set-foreground-window "SetForegroundWindow") com:bool
  (window com:hwnd))

(cffi:defcfun (set-process-dpi-aware "SetProcessDPIAware") com:bool)

(cffi:defcfun (set-process-dpi-awareness-context "SetProcessDpiAwarenessContext") com:bool
  (context dpi-awareness-context))

(cffi:defcfun (set-process-dpi-awareness "SetProcessDpiAwareness") com:hresult
  (awareness dpi-awareness))

(cffi:defcfun (set-window "SetWindowLongW") :int32
  (window com:hwnd)
  (index get-window-long)
  (new-long :int32))

(cffi:defcfun (set-window-pos "SetWindowPos") com:bool
  (window com:hwnd)
  (insert-after com:hwnd)
  (x :int32)
  (y :int32)
  (cx :int32)
  (cy :int32)
  (flags set-window-pos))

(cffi:defcfun (set-window-text "SetWindowTextW") com:bool
  (window com:hwnd)
  (title com:wstring))

(cffi:defcfun (show-window "ShowWindow") com:bool
  (window com:hwnd)
  (command show-command))

(cffi:defcfun (stretch-di-bits "StretchDIBits") :int32
  (device com:hdc)
  (xdest :int32)
  (ydest :int32)
  (wdest :int32)
  (hdest :int32)
  (xsrc :int32)
  (ysrc :int32)
  (wsrc :int32)
  (hsrc :int32)
  (bits (:pointer :void))
  ;; pointer to bitmap-info-header or bitmap-v5-header
  (bitmapinfo (:pointer #++(:struct bitmap-info-header)))
  (usage dib-usage)
  (rop rop-code))

(cffi:defcfun (to-unicode "ToUnicode") :int32
  (vk :uint32)
  (scan-code :uint32)
  (state (:pointer :uint8))
  (chars com:wstring)
  (buff-count :int32)
  (flags :uint32))

(cffi:defcfun (track-mouse-event "TrackMouseEvent") com:bool
  (event (:pointer (:struct track-mouse-event))))

(cffi:defcfun (translate-message "TranslateMessage") com:bool
  (message (:pointer (:struct message))))

(cffi:defcfun (validate-rect "ValidateRect") com:bool
  (window com:hwnd)
  (rect (:pointer (:struct rect))))

(cffi:defcfun (create-waitable-timer "CreateWaitableTimerW") com:handle
  (attributes (:pointer #++(:struct security-attributes)))
  (manual-reset com:bool)
  (timer-name com:wstring))

(cffi:defcfun (set-waitable-timer "SetWaitableTimer") com:bool
  (timer com:handle)
  (due-time (:pointer :int64))
  (period :long)
  (completion-routine :pointer) ;;((:pointer :void) :uint32 :uint32) -> :void
  (arg (:pointer :void))
  (resume com:bool))

(cffi:defcfun (cancel-waitable-timer "CancelWaitableTimer") com:bool
  (timer com:handle))

(cffi:defcfun (close-handle "CloseHandle") com:bool
  (handle com:handle))

(cffi:defcfun (destroy-icon "DestroyIcon") com:bool
  (handle com:hicon))

(cffi:defcfun (create-dib-section "CreateDIBSection") com:hbitmap
  (dc com:hdc)
  (bi (:pointer #++(:struct bitmap-info-header)))
  (usage dib-usage)
  (bits (:pointer (:pointer :void)))
  (section com:handle)
  (offset :uint32))

(cffi:defcfun (create-bitmap "CreateBitmap") com:hbitmap
  (width :int32)
  (height :int32)
  (planes :uint32)
  (bitcount :uint32)
  (bits (:pointer :void)))

(cffi:defcfun (create-icon "CreateIconIndirect") com:hicon
  (icon-info (:pointer (:struct icon-info))))

(cffi:defcfun (load-image "LoadImageW") com:handle
  (instance com:hinstance)
  (name cursor)
  (type load-image-type)
  (cx :int32)
  (cy :int32)
  (behavior load-image-behavior))

(cffi:defcfun (set-cursor "SetCursor") com:hcursor
  (cursor com:hcursor))

(cffi:defcfun (open-clipboard "OpenClipboard") com:bool
  (handle com:hwnd))

(cffi:defcfun (enum-clipboard-formats "EnumClipboardFormats") clipboard-format
  (format clipboard-format))

(cffi:defcfun (get-clipboard-data "GetClipboardData") com:handle
  (format clipboard-format))

(cffi:defcfun (close-clipboard "CloseClipboard") com:bool)

(cffi:defcfun (empty-clipboard "EmptyClipboard") com:bool)

(cffi:defcfun (set-clipboard-data "SetClipboardData") com:handle
  (format clipboard-format)
  (data com:handle))

(cffi:defcfun (global-alloc "GlobalAlloc") com:hglobal
  (flags global-alloc-flags)
  (size :size))

(cffi:defcfun (delete-object "DeleteObject") com:bool
  (handle com:hgdiobj))

(cffi:defcfun (global-lock "GlobalLock") (:pointer :void)
  (handle com:hglobal))

(cffi:defcfun (global-unlock "GlobalUnlock") com:bool
  (handle com:hglobal))

(cffi:defcfun (drag-query-point "DragQueryPoint") com:bool
  (handle com:hdrop)
  (point (:pointer #++(:struct point))))

(cffi:defcfun (drag-query-file "DragQueryFileW") :uint32
  (handle com:hdrop)
  (file :uint32)
  (buf com:wstring)
  (size :uint32))

(cffi:defcfun (drag-finish "DragFinish") :void
  (handle com:hdrop))

(cffi:defcfun (drag-accept-files "DragAcceptFiles") :void
  (handle com:hwnd)
  (mode com:bool))

(cffi:defcfun ("DwmFlush" dwm-flush) com:hresult)

(cffi:defcfun ("DwmIsCompositionEnabled" %dwm-is-composition-enabled)
    com:hresult
  (enabled (:pointer com:bool)))
