(in-package #:org.shirakumo.framebuffers.mezzano)

(defvar *keytable* (make-hash-table :test 'eql))
(defvar *codetable* (make-hash-table :test 'eq))

(defun init-keytable ()
  (loop for (char . key) in '((#\0 . :0)
                              (#\1 . :1)
                              (#\2 . :2)
                              (#\3 . :3)
                              (#\4 . :4)
                              (#\5 . :5)
                              (#\6 . :6)
                              (#\7 . :7)
                              (#\8 . :8)
                              (#\9 . :9)
                              (#\A . :a)
                              (#\B . :b)
                              (#\C . :c)
                              (#\D . :d)
                              (#\E . :e)
                              (#\F . :f)
                              (#\G . :g)
                              (#\H . :h)
                              (#\I . :i)
                              (#\J . :j)
                              (#\K . :k)
                              (#\L . :l)
                              (#\M . :m)
                              (#\N . :n)
                              (#\O . :o)
                              (#\P . :p)
                              (#\Q . :q)
                              (#\R . :r)
                              (#\S . :s)
                              (#\T . :t)
                              (#\U . :u)
                              (#\V . :v)
                              (#\W . :w)
                              (#\X . :x)
                              (#\Y . :y)
                              (#\Z . :z)
                              (#\- . :minus)
                              (#\= . :equal)
                              (#\[ . :left-bracket)
                              (#\] . :right-bracket)
                              (#\; . :semicolon)
                              (#\' . :apostrophe)
                              (#\, . :comma)
                              (#\. . :period)
                              (#\/ . :slash)
                              (#\\ . :backslash)
                              (#\Esc . :escape)
                              (#\Backspace . :Backspace)
                              (#\Tab . :Tab)
                              (#\Newline . :enter)
                              (#\Space . :Space)
                              (#\F1 . :F1)
                              (#\F2 . :F2)
                              (#\F3 . :F3)
                              (#\F4 . :F4)
                              (#\F5 . :F5)
                              (#\F6 . :F6)
                              (#\F7 . :F7)
                              (#\F8 . :F8)
                              (#\F9 . :F9)
                              (#\F10 . :F10)
                              (#\F11 . :F11)
                              (#\F12 . :F12)
                              (#\KP-0 . :kp-0)
                              (#\KP-1 . :kp-1)
                              (#\KP-2 . :kp-2)
                              (#\KP-3 . :kp-3)
                              (#\KP-4 . :kp-4)
                              (#\KP-5 . :kp-5)
                              (#\KP-6 . :kp-6)
                              (#\KP-7 . :kp-7)
                              (#\KP-8 . :kp-8)
                              (#\KP-9 . :kp-9)
                              (#\KP-Minus . :kp-subtract)
                              (#\KP-Plus . :kp-add)
                              (#\KP-Period . :kp-decimal)
                              (#\KP-Multiply . :kp-multiply)
                              (#\KP-Divide . :kp-divide)
                              (#\KP-Enter . :kp-enter)
                              (#\Menu . :Menu)
                              (#\Insert . :insert)
                              (#\Home . :home)
                              (#\Page-Up . :Page-Up)
                              (#\Delete . :Delete)
                              (#\End . :End)
                              (#\Page-Down . :Page-Down)
                              (#\Up-Arrow . :Up)
                              (#\Left-Arrow . :Left)
                              (#\Down-Arrow . :Down)
                              (#\Right-Arrow . :Right)
                              (#\Pause . :Pause)
                              (#\Print-Screen . :Print-Screen)
                              (#\Scroll-Lock . :Scroll-Lock))
        do (setf (gethash (char-code char) *keytable*) key)
           (setf (gethash key *codetable*) (char-code char))))

(init-keytable)

(defun translate-key (key)
  (gethash (char-code key) *keytable*))

